import type React from 'react';
import { COLORS, FONTS, RADIUS, SHADOW } from '../../constants/theme';

// ==========================================
// webStyles — equivalente web de StyleSheet.create() usado en el APK.
// Centraliza todos los estilos inline en un único diccionario reutilizable,
// manteniendo el mismo patrón mental que el equipo ya usa en React Native.
// ==========================================
export const webStyles: { [key: string]: React.CSSProperties } = {
  // ---------- Estados globales ----------
  centerContainer: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    height: '100vh',
    backgroundColor: COLORS.crema,
    fontFamily: FONTS.body,
  },

  // ---------- Auth ----------
  authBackground: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    minHeight: '100vh',
    backgroundColor: COLORS.chocolateOscuro,
    backgroundImage: `radial-gradient(${COLORS.moca}55 1.5px, transparent 1.5px)`,
    backgroundSize: '26px 26px',
    fontFamily: FONTS.body,
    padding: '24px',
  },
  authCard: {
    backgroundColor: COLORS.crema,
    borderRadius: RADIUS.xl,
    padding: '40px',
    width: '100%',
    maxWidth: '430px',
    boxShadow: SHADOW.modal,
    border: `1px solid ${COLORS.vainilla}`,
  },
  authEyebrow: {
    color: COLORS.caramelo,
    fontWeight: 800,
    fontSize: '11px',
    letterSpacing: '2px',
    textTransform: 'uppercase',
    textAlign: 'center',
    display: 'block',
    marginBottom: '6px',
  },
  authTitle: {
    fontFamily: FONTS.display,
    color: COLORS.chocolate,
    fontSize: '26px',
    fontWeight: 600,
    margin: '4px 0 8px',
    textAlign: 'center',
  },
  authSubtitle: {
    color: COLORS.moca,
    fontSize: '14px',
    margin: 0,
    lineHeight: 1.5,
    textAlign: 'center',
  },
  inputGroup: { display: 'flex', flexDirection: 'column', gap: '6px' },
  label: {
    color: COLORS.chocolate,
    fontSize: '12.5px',
    fontWeight: 700,
    letterSpacing: '0.2px',
  },
  input: {
    padding: '12px 14px',
    borderRadius: RADIUS.sm,
    border: `1.5px solid ${COLORS.vainilla}`,
    fontSize: '14px',
    fontFamily: FONTS.body,
    backgroundColor: COLORS.blanco,
    color: COLORS.chocolate,
    width: '100%',
  },
  primaryBtn: {
    backgroundColor: COLORS.chocolate,
    color: COLORS.blanco,
    padding: '14px',
    border: 'none',
    borderRadius: RADIUS.md,
    fontWeight: 700,
    fontSize: '14px',
    fontFamily: FONTS.body,
    cursor: 'pointer',
    boxShadow: '0 6px 16px rgba(65, 44, 39, 0.22)',
  },
  linkBtn: {
    background: 'none',
    border: 'none',
    color: COLORS.moca,
    fontWeight: 700,
    cursor: 'pointer',
    fontSize: '13px',
    fontFamily: FONTS.body,
  },
  errorBox: {
    backgroundColor: '#FADBD8',
    color: COLORS.rojo,
    padding: '12px 14px',
    borderRadius: RADIUS.sm,
    fontSize: '13px',
    fontWeight: 600,
    border: `1px solid ${COLORS.rojo}33`,
  },
  successBox: {
    backgroundColor: '#D4EFDF',
    color: COLORS.verde,
    padding: '12px 14px',
    borderRadius: RADIUS.sm,
    fontSize: '13px',
    fontWeight: 600,
    border: `1px solid ${COLORS.verde}33`,
  },

  // ---------- Layout general ----------
  webLayout: {
    backgroundColor: COLORS.crema,
    minHeight: '100vh',
    fontFamily: FONTS.body,
  },
  header: {
    backgroundColor: COLORS.fondoHeader,
    borderBottom: `1px solid ${COLORS.vainilla}`,
    padding: '14px 32px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    position: 'sticky',
    top: 0,
    zIndex: 100,
    backdropFilter: 'saturate(1.1)',
  },
  onlineTag: {
    backgroundColor: COLORS.verde,
    color: COLORS.blanco,
    fontSize: '11px',
    fontWeight: 700,
    padding: '4px 11px',
    borderRadius: RADIUS.pill,
    letterSpacing: '0.3px',
  },
  headerNavBtn: {
    backgroundColor: COLORS.chocolate,
    color: COLORS.blanco,
    border: 'none',
    padding: '9px 16px',
    borderRadius: RADIUS.sm,
    fontSize: '12px',
    fontWeight: 700,
    fontFamily: FONTS.body,
    cursor: 'pointer',
  },
  logoutBtn: {
    backgroundColor: COLORS.rojo,
    color: COLORS.blanco,
    border: 'none',
    padding: '9px 16px',
    borderRadius: RADIUS.sm,
    fontSize: '12px',
    fontWeight: 700,
    fontFamily: FONTS.body,
    cursor: 'pointer',
  },
  mainContent: {
    padding: '32px 24px 90px',
    maxWidth: '1200px',
    margin: '0 auto',
  },
  sectionTitle: {
    fontFamily: FONTS.display,
    color: COLORS.chocolate,
    fontSize: '22px',
    fontWeight: 600,
    margin: '0 0 6px',
  },

  // ---------- Tabs ----------
  tabBar: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '20px',
    gap: '12px',
    flexWrap: 'wrap',
  },
  mainTabGroup: {
    display: 'flex',
    backgroundColor: COLORS.vainilla,
    padding: '4px',
    borderRadius: RADIUS.md,
    flex: 1,
    maxWidth: '320px',
  },
  tabBtn: {
    flex: 1,
    padding: '10px',
    border: 'none',
    borderRadius: RADIUS.sm,
    background: 'none',
    color: COLORS.chocolate,
    fontWeight: 700,
    fontSize: '13px',
    fontFamily: FONTS.body,
    cursor: 'pointer',
  },
  activeTabBtn: {
    backgroundColor: COLORS.chocolate,
    color: COLORS.blanco,
    boxShadow: '0 3px 10px rgba(65, 44, 39, 0.2)',
  },
  historialTabBtn: {
    backgroundColor: COLORS.vainilla,
    color: COLORS.chocolate,
    border: 'none',
    padding: '10px 18px',
    borderRadius: RADIUS.md,
    fontWeight: 700,
    fontSize: '13px',
    fontFamily: FONTS.body,
    cursor: 'pointer',
  },
  activeHistorialBtn: {
    backgroundColor: COLORS.moca,
    color: COLORS.blanco,
  },
  searchInput: {
    width: '100%',
    padding: '14px 16px',
    borderRadius: RADIUS.md,
    border: `1.5px solid ${COLORS.vainilla}`,
    fontSize: '14px',
    fontFamily: FONTS.body,
    marginBottom: '24px',
    boxSizing: 'border-box',
    backgroundColor: COLORS.blanco,
    color: COLORS.chocolate,
  },

  // ---------- Grid de pedidos ----------
  pedidosGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(330px, 1fr))',
    gap: '20px',
  },
  pedidoCard: {
    backgroundColor: COLORS.blanco,
    borderRadius: RADIUS.lg,
    border: `1px solid ${COLORS.vainilla}`,
    padding: '20px',
    cursor: 'pointer',
    boxShadow: SHADOW.card,
    display: 'flex',
    flexDirection: 'column',
  },
  emptyBox: {
    textAlign: 'center',
    padding: '70px 20px',
    color: COLORS.moca,
    backgroundColor: COLORS.blanco,
    borderRadius: RADIUS.lg,
    border: `1.5px dashed ${COLORS.vainilla}`,
    gridColumn: '1 / -1',
    fontWeight: 600,
  },
  chip: {
    color: COLORS.blanco,
    padding: '5px 12px',
    borderRadius: RADIUS.sm,
    fontSize: '11px',
    fontWeight: 700,
    letterSpacing: '0.4px',
  },
  actionChipBtn: {
    backgroundColor: COLORS.caramelo,
    color: COLORS.chocolate,
    border: 'none',
    padding: '5px 12px',
    borderRadius: RADIUS.sm,
    fontSize: '11px',
    fontWeight: 700,
    fontFamily: FONTS.body,
    cursor: 'pointer',
  },
  trackChipBtn: {
    backgroundColor: COLORS.verde,
    color: COLORS.blanco,
    border: 'none',
    padding: '5px 12px',
    borderRadius: RADIUS.sm,
    fontSize: '11px',
    fontWeight: 700,
    fontFamily: FONTS.body,
    cursor: 'pointer',
  },
  etaBox: {
    backgroundColor: '#E8F8F5',
    color: COLORS.verde,
    padding: '8px 12px',
    borderRadius: RADIUS.sm,
    fontSize: '12px',
    fontWeight: 700,
    marginTop: '10px',
    border: `1px solid ${COLORS.verde}22`,
  },
  fabBtn: {
    position: 'fixed',
    right: '32px',
    bottom: '32px',
    width: '64px',
    height: '64px',
    borderRadius: RADIUS.pill,
    backgroundColor: COLORS.chocolate,
    color: COLORS.blanco,
    fontSize: '30px',
    border: 'none',
    cursor: 'pointer',
    boxShadow: SHADOW.fab,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 90,
  },

  // ---------- Catálogo ----------
  catalogoContainer: {
    backgroundColor: COLORS.blanco,
    padding: '28px',
    borderRadius: RADIUS.xl,
    border: `1px solid ${COLORS.vainilla}`,
    boxShadow: SHADOW.card,
  },
  catalogoGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(290px, 1fr))',
    gap: '18px',
  },
  catalogCard: {
    border: `1px solid ${COLORS.vainilla}`,
    borderRadius: RADIUS.md,
    padding: '16px',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    gap: '14px',
    backgroundColor: COLORS.blanco,
  },
  categoryBadge: {
    backgroundColor: COLORS.fondoHeader,
    color: COLORS.chocolate,
    padding: '3px 10px',
    borderRadius: '6px',
    fontSize: '11px',
    fontWeight: 700,
  },
  priceBox: {
    backgroundColor: COLORS.crema,
    padding: '10px 14px',
    borderRadius: RADIUS.sm,
    marginTop: '8px',
    border: `1px solid ${COLORS.vainilla}66`,
  },
  editPriceBtn: {
    backgroundColor: COLORS.vainilla,
    color: COLORS.chocolate,
    border: 'none',
    padding: '5px 12px',
    borderRadius: RADIUS.sm,
    fontSize: '12px',
    fontWeight: 700,
    fontFamily: FONTS.body,
    cursor: 'pointer',
  },
  saveSmallBtn: {
    backgroundColor: COLORS.verde,
    color: COLORS.blanco,
    border: 'none',
    padding: '5px 10px',
    borderRadius: '6px',
    fontWeight: 700,
    cursor: 'pointer',
  },
  cancelSmallBtn: {
    backgroundColor: COLORS.rojo,
    color: COLORS.blanco,
    border: 'none',
    padding: '5px 10px',
    borderRadius: '6px',
    fontWeight: 700,
    cursor: 'pointer',
  },

  // ---------- Modales ----------
  modalOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(44, 29, 25, 0.6)',
    backdropFilter: 'blur(4px)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
    padding: '20px',
  },
  modalContent: {
    backgroundColor: COLORS.crema,
    padding: '28px',
    borderRadius: RADIUS.xl,
    maxWidth: '480px',
    width: '100%',
    maxHeight: '88vh',
    overflowY: 'auto',
    boxShadow: SHADOW.modal,
    border: `1px solid ${COLORS.vainilla}`,
  },
  modalTitle: {
    fontFamily: FONTS.display,
    color: COLORS.chocolate,
    fontSize: '20px',
    fontWeight: 600,
    margin: '0 0 4px',
  },
  statusBox: {
    backgroundColor: COLORS.vainilla,
    padding: '12px',
    borderRadius: RADIUS.sm,
    textAlign: 'center',
    fontWeight: 700,
    color: COLORS.chocolate,
    fontSize: '14px',
  },
  gpsTrackLine: {
    position: 'relative',
    height: '56px',
    backgroundColor: COLORS.vainilla,
    borderRadius: RADIUS.pill,
    marginTop: '20px',
    overflow: 'hidden',
  },
  scooterIcon: {
    position: 'absolute',
    top: '12px',
    fontSize: '26px',
  },
  modalCloseBtn: {
    backgroundColor: COLORS.chocolate,
    color: COLORS.blanco,
    border: 'none',
    padding: '14px',
    borderRadius: RADIUS.md,
    fontWeight: 700,
    fontSize: '14px',
    fontFamily: FONTS.body,
    width: '100%',
    cursor: 'pointer',
    marginTop: '18px',
  },
  chipOptionBtn: {
    padding: '8px 14px',
    borderRadius: RADIUS.sm,
    border: `1.5px solid ${COLORS.vainilla}`,
    background: COLORS.blanco,
    color: COLORS.moca,
    fontWeight: 700,
    fontSize: '12px',
    fontFamily: FONTS.body,
    cursor: 'pointer',
  },
  chipOptionSelected: {
    backgroundColor: COLORS.chocolate,
    color: COLORS.blanco,
    borderColor: COLORS.chocolate,
  },
  itemsSelectorBox: {
    maxHeight: '210px',
    overflowY: 'auto',
    border: `1.5px solid ${COLORS.vainilla}`,
    borderRadius: RADIUS.md,
    padding: '10px',
    backgroundColor: COLORS.blanco,
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  itemSelectorRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  productPickBtn: {
    background: 'none',
    border: 'none',
    textAlign: 'left',
    cursor: 'pointer',
    fontSize: '13px',
    fontFamily: FONTS.body,
    color: COLORS.chocolate,
    width: '100%',
  },
  productPickSelected: {
    fontWeight: 700,
    color: COLORS.verde,
  },
  qtyMiniBtn: {
    backgroundColor: COLORS.vainilla,
    border: 'none',
    padding: '3px 10px',
    borderRadius: '6px',
    cursor: 'pointer',
    fontWeight: 700,
    color: COLORS.chocolate,
  },
  summaryBoxModal: {
    backgroundColor: COLORS.fondoHeader,
    padding: '14px',
    borderRadius: RADIUS.md,
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
    fontSize: '13px',
    color: COLORS.chocolate,
    border: `1px solid ${COLORS.vainilla}`,
  },
  deleteBtnModal: {
    backgroundColor: COLORS.rojo,
    color: COLORS.blanco,
    border: 'none',
    padding: '12px',
    borderRadius: RADIUS.sm,
    fontWeight: 700,
    fontFamily: FONTS.body,
    cursor: 'pointer',
  },
  cancelBtnModal: {
    backgroundColor: COLORS.vainilla,
    color: COLORS.chocolate,
    border: 'none',
    padding: '12px',
    borderRadius: RADIUS.sm,
    fontWeight: 700,
    fontFamily: FONTS.body,
    cursor: 'pointer',
  },


  posGrid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(110px, 1fr))', gap: '8px', marginTop: '5px' },
  posItem: { padding: '10px 8px', borderRadius: '12px', border: `2px solid #E3C9B3`, backgroundColor: '#FFF', cursor: 'pointer', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', textAlign: 'center', height: '110px', boxShadow: '0 4px 10px rgba(65, 44, 39, 0.05)', transition: 'all 0.2s ease' },
  posItemSelected: { borderColor: '#5B8A5A', backgroundColor: '#F0F9F0', transform: 'scale(0.98)' },
  posItemTitle: { fontSize: '13px', fontWeight: 'bold', color: '#412C27', marginBottom: '6px', lineHeight: '1.2' },
  posItemPrice: { fontSize: '12px', color: '#A67B5B', fontWeight: 'bold' },
  posCategoryTitle: { gridColumn: '1 / -1', fontSize: '16px', fontWeight: 'bold', color: '#412C27', marginTop: '10px', borderBottom: `2px solid #FFF3D8`, paddingBottom: '6px' },
  qtyPosBtn: { backgroundColor: '#412C27', color: '#FFF', border: 'none', width: '28px', height: '28px', borderRadius: '6px', cursor: 'pointer', fontWeight: 'bold', fontSize: '16px', display: 'flex', alignItems: 'center', justifyContent: 'center' },
  posQtyValue: { fontWeight: '900', fontSize: '16px', color: '#412C27' },
  
  quickStatusBtn: { padding: '16px', borderRadius: '12px', border: 'none', color: '#FFF', fontWeight: 'bold', fontSize: '15px', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '10px', width: '100%', marginBottom: '10px', boxShadow: '0 4px 12px rgba(0,0,0,0.1)' },
  closeXBtn: { position: 'absolute', top: '15px', right: '15px', background: 'none', border: 'none', fontSize: '24px', color: '#A67B5B', cursor: 'pointer' },
  // NUEVOS ESTILOS PARA CHAT, CIERRE Y NOTIFICACIONES
  toast: { position: 'fixed', top: '92px', right: '24px', backgroundColor: COLORS.chocolate, color: COLORS.blanco, padding: '16px 18px', borderRadius: '12px', boxShadow: '0 8px 24px rgba(0,0,0,0.25)', zIndex: 9999, display: 'flex', alignItems: 'flex-start', gap: '12px', maxWidth: '320px', animation: 'bk-overlay-in 0.3s ease' },
  badge: { position: 'absolute', top: '-5px', right: '-5px', backgroundColor: COLORS.rojo, color: COLORS.blanco, fontSize: '10px', fontWeight: 'bold', padding: '2px 6px', borderRadius: '10px' },
  chatPanel: { position: 'fixed', bottom: '20px', right: '20px', width: '320px', height: '450px', backgroundColor: COLORS.crema, borderRadius: '16px', boxShadow: '0 10px 30px rgba(0,0,0,0.3)', display: 'flex', flexDirection: 'column', zIndex: 1000, border: `2px solid ${COLORS.vainilla}`, overflow: 'hidden' },
  chatHeader: { backgroundColor: COLORS.chocolate, color: COLORS.blanco, padding: '12px', fontWeight: 'bold', display: 'flex', justifyContent: 'space-between', alignItems: 'center' },
  chatBody: { flex: 1, padding: '12px', overflowY: 'auto', display: 'flex', flexDirection: 'column', gap: '8px' },
  chatMsg: { padding: '8px 12px', borderRadius: '12px', maxWidth: '85%', fontSize: '13px' },
  chatInputRow: { display: 'flex', padding: '10px', backgroundColor: COLORS.blanco, borderTop: `1px solid ${COLORS.vainilla}` },
};